# CONFIGURACIÓN DE BASE DE DATOS
spring.datasource.url=jdbc:mysql://localhost:3306/sabor_gourmet_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Lmtlf1620*

# CONFIGURACIÓN DE JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# CONFIGURACIÓN DE JWT
jwt.secret=Y29tLnNhYm9yX2dvdXJtZXQuY2xhdmUubWFyYXZpbGxvc2E2MDI1NDg5MTI1
jwt.expiration=3600000